{-# LANGUAGE FlexibleInstances #-}

module HTML where

import Text.Parsec
import Data


class HTML a where
  renderHTML :: a -> String

instance HTML (Either ParseError Skriptum)
  where renderHTML (Left msg) = "<p style=\"color:red\">"++
                                    renderHTML (take 80 (show msg) ++ "...")++
                                "</p>"
        renderHTML (Right skrpt) = renderHTML skrpt

instance HTML Skriptum
  where renderHTML (Skriptum a t s j p ty) = italic (renderHTML a)++", "++
                                             bold   (renderHTML t)++
                                                     renderHTML s ++
                                                     renderHTML j ++
                                                     renderHTML p ++
                                                     renderHTML ty
                                           where bold   text = "<b>"++text++"</b>"
                                                 italic text = "<i>"++text++"</i>"

instance (HTML a) => HTML (Maybe a)
  where renderHTML Nothing = ""
        renderHTML (Just a) = renderHTML a

instance HTML Semester
  where renderHTML WS = ", WS"
        renderHTML SS = ", SS"

instance HTML Jahr
  where renderHTML (J j) = ' ':show j

instance HTML Page
  where renderHTML (P p) = ", p. "++show p

instance HTML Typ
  where renderHTML t = " ("++renderHTML (show t)++")"

instance HTML String
  where renderHTML = concatMap escape

escape :: Char -> String
escape '"' = "&quot;"
escape '\''= "&apos;"
escape '&' = "&amp;"
escape '<' = "&lt;"
escape '>' = "&gt;"
escape ' ' = "&nbsp;"
escape '¡' = "&iexcl;"
escape '¢' = "&cent;"
escape '£' = "&pound;"
escape '¤' = "&curren;"
escape '¥' = "&yen;"
escape '¦' = "&brvbar;"
escape '§' = "&sect;"
escape '¨' = "&uml;"
escape '©' = "&copy;"
escape 'ª' = "&ordf;"
escape '«' = "&laquo;"
escape '¬' = "&not;"
escape '�' = "&shy;"
escape '®' = "&reg;"
escape '¯' = "&macr;"
escape '°' = "&deg;"
escape '±' = "&plusmn;"
escape '²' = "&sup2;"
escape '³' = "&sup3;"
escape '´' = "&acute;"
escape 'µ' = "&micro;"
escape '¶' = "&para;"
escape '·' = "&middot;"
escape '¸' = "&cedil;"
escape '¹' = "&sup1;"
escape 'º' = "&ordm;"
escape '»' = "&raquo;"
escape '¼' = "&frac14;"
escape '½' = "&frac12;"
escape '¾' = "&frac34;"
escape '¿' = "&iquest;"
escape '×' = "&times;"
escape '÷' = "&divide;"
escape 'À' = "&Agrave;"
escape 'Á' = "&Aacute;"
escape 'Â' = "&Acirc;"
escape 'Ã' = "&Atilde;"
escape 'Ä' = "&Auml;"
escape 'Å' = "&Aring;"
escape 'Æ' = "&AElig;"
escape 'Ç' = "&Ccedil;"
escape 'È' = "&Egrave;"
escape 'É' = "&Eacute;"
escape 'Ê' = "&Ecirc;"
escape 'Ë' = "&Euml;"
escape 'Ì' = "&Igrave;"
escape 'Í' = "&Iacute;"
escape 'Î' = "&Icirc;"
escape 'Ï' = "&Iuml;"
escape 'Ð' = "&ETH;"
escape 'Ñ' = "&Ntilde;"
escape 'Ò' = "&Ograve;"
escape 'Ó' = "&Oacute;"
escape 'Ô' = "&Ocirc;"
escape 'Õ' = "&Otilde;"
escape 'Ö' = "&Ouml;"
escape 'Ø' = "&Oslash;"
escape 'Ù' = "&Ugrave;"
escape 'Ú' = "&Uacute;"
escape 'Û' = "&Ucirc;"
escape 'Ü' = "&Uuml;"
escape 'Ý' = "&Yacute;"
escape 'Þ' = "&THORN;"
escape 'ß' = "&szlig;"
escape 'à' = "&agrave;"
escape 'á' = "&aacute;"
escape 'â' = "&acirc;"
escape 'ã' = "&atilde;"
escape 'ä' = "&auml;"
escape 'å' = "&aring;"
escape 'æ' = "&aelig;"
escape 'ç' = "&ccedil;"
escape 'è' = "&egrave;"
escape 'é' = "&eacute;"
escape 'ê' = "&ecirc;"
escape 'ë' = "&euml;"
escape 'ì' = "&igrave;"
escape 'í' = "&iacute;"
escape 'î' = "&icirc;"
escape 'ï' = "&iuml;"
escape 'ð' = "&eth;"
escape 'ñ' = "&ntilde;"
escape 'ò' = "&ograve;"
escape 'ó' = "&oacute;"
escape 'ô' = "&ocirc;"
escape 'õ' = "&otilde;"
escape 'ö' = "&ouml;"
escape 'ø' = "&oslash;"
escape 'ù' = "&ugrave;"
escape 'ú' = "&uacute;"
escape 'û' = "&ucirc;"
escape 'ü' = "&uuml;"
escape 'ý' = "&yacute;"
escape 'þ' = "&thorn;"
escape 'ÿ' = "&yuml;"
escape x = [x]

urlEscape :: String -> String
urlEscape = concatMap urlEscape'
  where urlEscape' ' ' = "%20"
--        urlEscape' '!' = "%21"
--        urlEscape' '"' = "%22"
--        urlEscape' '#' = "%23"
--        urlEscape' '$' = "%24"
--        urlEscape' '%' = "%25"
--        urlEscape' '&' = "%26"
--        urlEscape' '\''= "%27"
--        urlEscape' '(' = "%28"
--        urlEscape' ')' = "%29"
--        urlEscape' '*' = "%2A"
--        urlEscape' '+' = "%2B"
--        urlEscape' ',' = "%2C"
--        urlEscape' '-' = "%2D"
--        urlEscape' '.' = "%2E"
--        urlEscape' '/' = "%2F"
--        urlEscape' '0' = "%30"
--        urlEscape' '1' = "%31"
--        urlEscape' '2' = "%32"
--        urlEscape' '3' = "%33"
--        urlEscape' '4' = "%34"
--        urlEscape' '5' = "%35"
--        urlEscape' '6' = "%36"
--        urlEscape' '7' = "%37"
--        urlEscape' '8' = "%38"
--        urlEscape' '9' = "%39"
--        urlEscape' ':' = "%3A"
--        urlEscape' ';' = "%3B"
--        urlEscape' '<' = "%3C"
--        urlEscape' '=' = "%3D"
--        urlEscape' '>' = "%3E"
--        urlEscape' '?' = "%3F"
--        urlEscape' '@' = "%40"
--        urlEscape' 'A' = "%41"
--        urlEscape' 'B' = "%42"
--        urlEscape' 'C' = "%43"
--        urlEscape' 'D' = "%44"
--        urlEscape' 'E' = "%45"
--        urlEscape' 'F' = "%46"
--        urlEscape' 'G' = "%47"
--        urlEscape' 'H' = "%48"
--        urlEscape' 'I' = "%49"
--        urlEscape' 'J' = "%4A"
--        urlEscape' 'K' = "%4B"
--        urlEscape' 'L' = "%4C"
--        urlEscape' 'M' = "%4D"
--        urlEscape' 'N' = "%4E"
--        urlEscape' 'O' = "%4F"
--        urlEscape' 'P' = "%50"
--        urlEscape' 'Q' = "%51"
--        urlEscape' 'R' = "%52"
--        urlEscape' 'S' = "%53"
--        urlEscape' 'T' = "%54"
--        urlEscape' 'U' = "%55"
--        urlEscape' 'V' = "%56"
--        urlEscape' 'W' = "%57"
--        urlEscape' 'X' = "%58"
--        urlEscape' 'Y' = "%59"
--        urlEscape' 'Z' = "%5A"
--        urlEscape' '[' = "%5B"
--        urlEscape' '\\' = "%5C"
--        urlEscape' ']' = "%5D"
--        urlEscape' '^' = "%5E"
--        urlEscape' '_' = "%5F"
--
--        urlEscape' 'a' = "%61"
--        urlEscape' 'b' = "%62"
--        urlEscape' 'c' = "%63"
--        urlEscape' 'd' = "%64"
--        urlEscape' 'e' = "%65"
--        urlEscape' 'f' = "%66"
--        urlEscape' 'g' = "%67"
--        urlEscape' 'h' = "%68"
--        urlEscape' 'i' = "%69"
--        urlEscape' 'j' = "%6A"
--        urlEscape' 'k' = "%6B"
--        urlEscape' 'l' = "%6C"
--        urlEscape' 'm' = "%6D"
--        urlEscape' 'n' = "%6E"
--        urlEscape' 'o' = "%6F"
--        urlEscape' 'p' = "%70"
--        urlEscape' 'q' = "%71"
--        urlEscape' 'r' = "%72"
--        urlEscape' 's' = "%73"
--        urlEscape' 't' = "%74"
--        urlEscape' 'u' = "%75"
--        urlEscape' 'v' = "%76"
--        urlEscape' 'w' = "%77"
--        urlEscape' 'x' = "%78"
--        urlEscape' 'y' = "%79"
--        urlEscape' 'z' = "%7A"
--        urlEscape' '{' = "%7B"
--        urlEscape' '|' = "%7C"
--        urlEscape' '}' = "%7D"
--        urlEscape' '~' = "%7E"
--
--
--
--        urlEscape' '‚' = "%82"
--        urlEscape' 'ƒ' = "%83"
--        urlEscape' '„' = "%84"
--        urlEscape' '…' = "%85"
--        urlEscape' '†' = "%86"
--        urlEscape' '‡' = "%87"
--        urlEscape' 'ˆ' = "%88"
--        urlEscape' '‰' = "%89"
--        urlEscape' 'Š' = "%8A"
--        urlEscape' '‹' = "%8B"
--        urlEscape' 'Œ' = "%8C"
--
--        urlEscape' 'Ž' = "%8E"
--
--
--        urlEscape' '‘' = "%91"
--        urlEscape' '’' = "%92"
--        urlEscape' '“' = "%93"
--        urlEscape' '”' = "%94"
--        urlEscape' '•' = "%95"
--        urlEscape' '–' = "%96"
--        urlEscape' '—' = "%97"
--        urlEscape' '˜' = "%98"
--        urlEscape' '™' = "%99"
--        urlEscape' 'š' = "%9A"
--        urlEscape' '›' = "%9B"
--        urlEscape' 'œ' = "%9C"
--
--        urlEscape' 'ž' = "%9E"
--        urlEscape' 'Ÿ' = "%9F"
--
--        urlEscape' '¡' = "%A1"
--        urlEscape' '¢' = "%A2"
--        urlEscape' '£' = "%A3"
--        urlEscape' '¤' = "%A4"
--        urlEscape' '¥' = "%A5"
--        urlEscape' '¦' = "%A6"
--        urlEscape' '§' = "%A7"
--        urlEscape' '¨' = "%A8"
--        urlEscape' '©' = "%A9"
--        urlEscape' 'ª' = "%AA"
--        urlEscape' '«' = "%AB"
--        urlEscape' '¬' = "%AC"
--
--        urlEscape' '®' = "%AE"
--        urlEscape' '¯' = "%AF"
--        urlEscape' '°' = "%B0"
--        urlEscape' '±' = "%B1"
--        urlEscape' '²' = "%B2"
--        urlEscape' '³' = "%B3"
--        urlEscape' '´' = "%B4"
--        urlEscape' 'µ' = "%B5"
--        urlEscape' '¶' = "%B6"
--        urlEscape' '·' = "%B7"
--        urlEscape' '¸' = "%B8"
--        urlEscape' '¹' = "%B9"
--        urlEscape' 'º' = "%BA"
--        urlEscape' '»' = "%BB"
--        urlEscape' '¼' = "%BC"
--        urlEscape' '½' = "%BD"
--        urlEscape' '¾' = "%BE"
--        urlEscape' '¿' = "%BF"
--        urlEscape' 'À' = "%C0"
--        urlEscape' 'Á' = "%C1"
--        urlEscape' 'Â' = "%C2"
--        urlEscape' 'Ã' = "%C3"
--        urlEscape' 'Ä' = "%C4"
--        urlEscape' 'Å' = "%C5"
--        urlEscape' 'Æ' = "%C6"
--        urlEscape' 'Ç' = "%C7"
--        urlEscape' 'È' = "%C8"
--        urlEscape' 'É' = "%C9"
--        urlEscape' 'Ê' = "%CA"
--        urlEscape' 'Ë' = "%CB"
--        urlEscape' 'Ì' = "%CC"
--        urlEscape' 'Í' = "%CD"
--        urlEscape' 'Î' = "%CE"
--        urlEscape' 'Ï' = "%CF"
--        urlEscape' 'Ð' = "%D0"
--        urlEscape' 'Ñ' = "%D1"
--        urlEscape' 'Ò' = "%D2"
--        urlEscape' 'Ó' = "%D3"
--        urlEscape' 'Ô' = "%D4"
--        urlEscape' 'Õ' = "%D5"
--        urlEscape' 'Ö' = "%D6"
--        urlEscape' '×' = "%D7"
--        urlEscape' 'Ø' = "%D8"
--        urlEscape' 'Ù' = "%D9"
--        urlEscape' 'Ú' = "%DA"
--        urlEscape' 'Û' = "%DB"
--        urlEscape' 'Ü' = "%DC"
--        urlEscape' 'Ý' = "%DD"
--        urlEscape' 'Þ' = "%DE"
--        urlEscape' 'ß' = "%DF"
--        urlEscape' 'à' = "%E0"
--        urlEscape' 'á' = "%E1"
--        urlEscape' 'â' = "%E2"
--        urlEscape' 'ã' = "%E3"
--        urlEscape' 'ä' = "%E4"
--        urlEscape' 'å' = "%E5"
--        urlEscape' 'æ' = "%E6"
--        urlEscape' 'ç' = "%E7"
--        urlEscape' 'è' = "%E8"
--        urlEscape' 'é' = "%E9"
--        urlEscape' 'ê' = "%EA"
--        urlEscape' 'ë' = "%EB"
--        urlEscape' 'ì' = "%EC"
--        urlEscape' 'í' = "%ED"
--        urlEscape' 'î' = "%EE"
--        urlEscape' 'ï' = "%EF"
--        urlEscape' 'ð' = "%F0"
--        urlEscape' 'ñ' = "%F1"
--        urlEscape' 'ò' = "%F2"
--        urlEscape' 'ó' = "%F3"
--        urlEscape' 'ô' = "%F4"
--        urlEscape' 'õ' = "%F5"
--        urlEscape' 'ö' = "%F6"
--        urlEscape' '÷' = "%F7"
--        urlEscape' 'ø' = "%F8"
--        urlEscape' 'ù' = "%F9"
--        urlEscape' 'ú' = "%FA"
--        urlEscape' 'û' = "%FB"
--        urlEscape' 'ü' = "%FC"
--        urlEscape' 'ý' = "%FD"
--        urlEscape' 'þ' = "%FE"
--        urlEscape' 'ÿ' = "%FF"
        urlEscape' x   = [x]
